name: Build and Test C++

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CMake and build tools
      run: sudo apt-get update && sudo apt-get install -y cmake g++ ninja-build

    - name: Create Build Directory
      run: mkdir build && cd build && cmake .. -G Ninja && ninja

    - name: Run Unit Tests
      run: cd build && ctest
